# Generated by Django 4.2.5 on 2023-10-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
